"""Generate the mock's Python casefold overrides and independent Python fixture.

Run from the repository root:
    python frontend\\scripts\\generate-curriculum-casefold.py

Uses only local Python/Node Unicode databases, never network data. The baseline is
CPython Unicode 15.1.0 and Node Unicode 17.0; updating them requires reviewing
backend Python compatibility and regenerating both artifacts. Node-only lowercase additions are overridden to
identity so a newer JS Unicode database cannot change the Python baseline.
"""

import json
from pathlib import Path
import subprocess
import unicodedata


ROOT = Path(__file__).resolve().parent.parent
if unicodedata.unidata_version != "15.1.0":
    raise SystemExit("Use Python with Unicode 15.1.0")
node_unicode = subprocess.check_output(
    ["node", "-p", "process.versions.unicode"], encoding="utf-8"
).strip()
if node_unicode != "17.0":
    raise SystemExit("Use Node with Unicode 17.0")
NODE_LOWERCASE_SCRIPT = "".join([
    "const pairs = []; for (let cp = 0; cp <= 0x10ffff; cp++) {",
    "const c = String.fromCodePoint(cp), lower = c.toLowerCase();",
    "if (c !== lower) pairs.push([c, lower]); }",
    "process.stdout.write(JSON.stringify(pairs));",
])
javascript_lower = dict(json.loads(subprocess.check_output(
    ["node", "-e", NODE_LOWERCASE_SCRIPT], encoding="utf-8"
)))
python_fold = {
    char: char.casefold()
    for cp in range(0x110000)
    if (char := chr(cp)).casefold() != char
}
characters = sorted(python_fold.keys() | javascript_lower.keys())
overrides = [
    (char, char.casefold()) for char in characters
    if char.casefold() != javascript_lower.get(char, char)
]


def literal(value):
    return json.dumps(value, ensure_ascii=True)


source = (
    "// Generated by scripts/generate-curriculum-casefold.py; Python Unicode 15.1.0.\n"
    "// Update from repo root: python frontend\\scripts\\generate-curriculum-casefold.py\n"
    "// Includes expansions, Cherokee uppercase folds, and newer-JS identity overrides.\n"
    "const casefoldOverrides = new Map<string, string>([\n"
    + "".join(f"  [{literal(char)}, {literal(fold)}],\n" for char, fold in overrides)
    + "])\n\n"
    "export function pythonCasefold(value: string): string {\n"
    "  return Array.from(value, (char) => casefoldOverrides.get(char) ?? char.toLowerCase()).join('')\n"
    "}\n"
)
(ROOT / "src" / "lib" / "curriculumCasefold.ts").write_text(source, encoding="utf-8")
(ROOT / "scripts" / "curriculum-casefold-fixture.json").write_text(
    '{\n  "unicode_version": "15.1.0",\n  "overrides": [\n'
    + ",\n".join(f"    {literal(pair)}" for pair in overrides)
    + '\n  ],\n  "folds": [\n'
    + ",\n".join(f"    {literal((char, char.casefold()))}" for char in characters)
    + "\n  ]\n}\n",
    encoding="utf-8",
)
print(f"Generated {len(overrides)} overrides and {len(characters)} Python casefold expectations")
