from backend.schemas.assignments import (
    AssignmentCreate,
    AssignmentListResponse,
    AssignmentRead,
    AssignmentStatusUpdate,
    AssignmentTargetRead,
    AssignmentUpdate,
)
from backend.schemas.auth import LoginRequest, LoginResponse, SessionResponse
from backend.schemas.calendar import (
    CalendarEventCreate,
    CalendarEventRead,
    CalendarEventUpdate,
    GradingPeriodCreate,
    GradingPeriodRead,
    GradingPeriodUpdate,
    InstructionalDayCount,
    SchoolYearCreate,
    SchoolYearDetail,
    SchoolYearRead,
    SchoolYearUpdate,
    TermCreate,
    TermRead,
    TermUpdate,
)
from backend.schemas.grades import (
    GradeAverageByStudent,
    GradeAverageBySubject,
    GradeCreate,
    GradeHistoryItem,
    GradeRead,
    GradeUpdate,
)
from backend.schemas.quizzes import QuizAttemptCreate, QuizAttemptRead, QuizCreate, QuizRead, QuizUpdate
from backend.schemas.students import StudentCreate, StudentRead, StudentUpdate
from backend.schemas.subjects import SubjectCreate, SubjectRead, SubjectUpdate
from backend.schemas.submissions import SubmissionRead

__all__ = [
    "AssignmentCreate",
    "AssignmentListResponse",
    "AssignmentRead",
    "AssignmentStatusUpdate",
    "AssignmentTargetRead",
    "AssignmentUpdate",
    "CalendarEventCreate",
    "CalendarEventRead",
    "CalendarEventUpdate",
    "GradeAverageByStudent",
    "GradeAverageBySubject",
    "GradeCreate",
    "GradeHistoryItem",
    "GradeRead",
    "GradeUpdate",
    "GradingPeriodCreate",
    "GradingPeriodRead",
    "GradingPeriodUpdate",
    "InstructionalDayCount",
    "LoginRequest",
    "LoginResponse",
    "QuizAttemptCreate",
    "QuizAttemptRead",
    "QuizCreate",
    "QuizRead",
    "QuizUpdate",
    "SessionResponse",
    "SchoolYearCreate",
    "SchoolYearDetail",
    "SchoolYearRead",
    "SchoolYearUpdate",
    "StudentCreate",
    "StudentRead",
    "StudentUpdate",
    "SubjectCreate",
    "SubjectRead",
    "SubjectUpdate",
    "SubmissionRead",
    "TermCreate",
    "TermRead",
    "TermUpdate",
]
