from backend.schemas.assignments import (
    AssignmentCreate,
    AssignmentListResponse,
    AssignmentRead,
    AssignmentStatusUpdate,
    AssignmentTargetRead,
    AssignmentUpdate,
)
from backend.schemas.attendance import (
    AttendanceDailyUpsert,
    AttendanceExcuseCreate,
    AttendanceExcuseRead,
    AttendanceHoursLog,
    AttendanceHoursResponse,
    AttendanceRecordRead,
    AttendanceSummaryBucket,
    AttendanceSummaryResponse,
)
from backend.schemas.auth import LoginRequest, LoginResponse, SessionResponse
from backend.schemas.backups import BackupConfigRead, BackupJobRead, BackupStatusRead, BackupTriggerRequest
from backend.schemas.calendar import (
    CalendarEventCreate,
    CalendarEventRead,
    CalendarEventUpdate,
    GradingPeriodCreate,
    GradingPeriodRead,
    GradingPeriodUpdate,
    InstructionalDayCount,
    SchoolYearCreate,
    SchoolYearDetail,
    SchoolYearRead,
    SchoolYearUpdate,
    TermCreate,
    TermRead,
    TermUpdate,
)
from backend.schemas.compliance import (
    ComplianceDashboardResponse,
    ComplianceDashboardStudent,
    ComplianceRuleCreate,
    ComplianceRuleListResponse,
    ComplianceRuleRead,
    ComplianceRuleSummary,
    ComplianceStatusRead,
    ComplianceStudentStatusResponse,
    FamilyComplianceStateRead,
    FamilyComplianceStateUpdate,
)
from backend.schemas.exports import ExportJobCreateRequest, ExportJobRead
from backend.schemas.grades import (
    GradeAverageByStudent,
    GradeAverageBySubject,
    GradeCreate,
    GradeHistoryItem,
    GradeRead,
    GradeUpdate,
)
from backend.schemas.gradebook import (
    GradeCategoryRead,
    GradeCategoryWrite,
    GradeScaleRead,
    GradeScaleWrite,
    GradebookCalculationRequest,
    GradebookCategoriesUpsert,
    GradebookScalesUpsert,
    GradebookSummary,
    GradebookTrends,
    GradebookView,
)
from backend.schemas.notifications import (
    NotificationListResponse,
    NotificationPreferenceRead,
    NotificationPreferenceUpdate,
    NotificationPreferenceUpdateRequest,
    NotificationRead,
    NotificationReadAllResponse,
    NotificationReadUpdate,
)
from backend.schemas.preferences import UserPreferencesRead, UserPreferencesUpdate
from backend.schemas.quizzes import QuizAttemptCreate, QuizAttemptRead, QuizCreate, QuizRead, QuizUpdate
from backend.schemas.report_cards import (
    ReportCardEntryRead,
    ReportCardGenerateRequest,
    ReportCardRead,
    ReportCardSummaryRead,
    ReportCardUpdateRequest,
)
from backend.schemas.students import StudentCreate, StudentRead, StudentUpdate
from backend.schemas.subjects import SubjectCreate, SubjectRead, SubjectUpdate
from backend.schemas.submissions import SubmissionRead

__all__ = [
    "AssignmentCreate",
    "AssignmentListResponse",
    "AssignmentRead",
    "AssignmentStatusUpdate",
    "AssignmentTargetRead",
    "AssignmentUpdate",
    "AttendanceDailyUpsert",
    "AttendanceExcuseCreate",
    "AttendanceExcuseRead",
    "AttendanceHoursLog",
    "AttendanceHoursResponse",
    "AttendanceRecordRead",
    "AttendanceSummaryBucket",
    "AttendanceSummaryResponse",
    "BackupConfigRead",
    "BackupJobRead",
    "BackupStatusRead",
    "BackupTriggerRequest",
    "CalendarEventCreate",
    "CalendarEventRead",
    "CalendarEventUpdate",
    "ComplianceDashboardResponse",
    "ComplianceDashboardStudent",
    "ComplianceRuleCreate",
    "ComplianceRuleListResponse",
    "ComplianceRuleRead",
    "ComplianceRuleSummary",
    "ComplianceStatusRead",
    "ComplianceStudentStatusResponse",
    "ExportJobCreateRequest",
    "ExportJobRead",
    "GradeAverageByStudent",
    "GradeAverageBySubject",
    "GradeCategoryRead",
    "GradeCategoryWrite",
    "GradeCreate",
    "GradeHistoryItem",
    "GradeRead",
    "GradeScaleRead",
    "GradeScaleWrite",
    "GradeUpdate",
    "GradebookCalculationRequest",
    "GradebookCategoriesUpsert",
    "GradebookScalesUpsert",
    "GradebookSummary",
    "GradebookTrends",
    "GradebookView",
    "GradingPeriodCreate",
    "GradingPeriodRead",
    "GradingPeriodUpdate",
    "InstructionalDayCount",
    "LoginRequest",
    "LoginResponse",
    "NotificationListResponse",
    "NotificationPreferenceRead",
    "NotificationPreferenceUpdate",
    "NotificationPreferenceUpdateRequest",
    "NotificationRead",
    "NotificationReadAllResponse",
    "NotificationReadUpdate",
    "UserPreferencesRead",
    "UserPreferencesUpdate",
    "FamilyComplianceStateRead",
    "FamilyComplianceStateUpdate",
    "QuizAttemptCreate",
    "QuizAttemptRead",
    "QuizCreate",
    "QuizRead",
    "QuizUpdate",
    "ReportCardEntryRead",
    "ReportCardGenerateRequest",
    "ReportCardRead",
    "ReportCardSummaryRead",
    "ReportCardUpdateRequest",
    "SessionResponse",
    "SchoolYearCreate",
    "SchoolYearDetail",
    "SchoolYearRead",
    "SchoolYearUpdate",
    "StudentCreate",
    "StudentRead",
    "StudentUpdate",
    "SubjectCreate",
    "SubjectRead",
    "SubjectUpdate",
    "SubmissionRead",
    "TermCreate",
    "TermRead",
    "TermUpdate",
]
